### ISSUE TITLE
SameSite not being set on sessionid

### ISSUE THREAD

**Issue by Gee19** [jotes/django-cookies-samesite#1]
* django-cookies-samesite version: 0.1.2
* Django version: 1.11.13
* Python version: 2.7.10
* Operating System: MacOS

### Description

First of all, thanks for sharing this <3

I've added the middleware and this to my settings file as per the docs:
```python
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE_KEYS = ['sde-csrftoken']
```

It seems the SameSite flag is only being set on keys in `SESSION_COOKIE_SAMESITE_KEYS` and not on `sessionid`.

See screenshot:
![samesite](https://user-images.githubusercontent.com/5077424/41643161-7c5bcee0-7438-11e8-963c-91c173ae9656.png)

PS: You should add a license to this project :)

**Comment by jotes** [comment]
Hi @Gee19!

I tried to reproduce your error on my local machine and there's only one scenario that comes to my mind.

Could you check the order of middlewares in your project?
`django_cookies_samesite.middleware.CookiesSameSite` should be above `django.contrib.sessions.middleware.SessionMiddleware`.

If it's not then middleware will behave as you described and `sessionid` cookie will not have `samesite` attribute.

I'm sorry if that wasn't clearly described in the Readme.

**Comment by Gee19** [comment]
This solved my issue :) Thanks.
