### ISSUE TITLE
Can't set cookie for csrftoken

### ISSUE THREAD

**Issue by sillycube** [jotes/django-cookies-samesite#16]
* django-cookies-samesite version: 0.4
* Django version: 1.11
* Python version: 3.7
* Operating System: Ubuntu18.04

### Description

I tried to install and add the below config in settings. But the csrftoken cookie can't be set with SameSite=None;Secure. SameSite and Secure are empty

### What I Did
in settings.py
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE_FORCE_ALL = True

'django_cookies_samesite.middleware.CookiesSameSite' is set to be the first item of MIDDLEWARE

**Comment by jotes** [comment]
@sillycube Thank you for you report, I'll look into that today.

**Comment by jotes** [comment]
@sillycube sorry for making you wait. I've tried to reproduce this problem via unit tests, but I couldn't reproduce it.
I'll try today to check this problem on the living app. I have a question in the meantime:
Does this problem affect only the CSRFToken cookie or all of them?

**Comment by sillycube** [comment]
I check that sessionid is not affected. SameSite and Secure can be set. I turn out using CSRF_USE_SESSIONS to put csrf token from cookie to session and the problem is solved.

**Comment by jotes** [comment]
Okay, I'm closing this issue then (feel free to re-open if the problem resurfaces again).
