### ISSUE TITLE
Disable SameSite for incompatible clients.

### ISSUE THREAD

**Issue by abdul-rafiu** [jotes/django-cookies-samesite#22]
* django-cookies-samesite version: 0.5.1
* Django version: all
* Python version: all

### Description

Google released the incompatible client list for SameSite policy. Currently, we are disabling only for Chrome version 51 - 66. We have to extend this to all the incompatible clients. Check the link given below.

[Incompatible Clients](https://www.chromium.org/updates/same-site/incompatible-clients)

**Comment by abdul-rafiu** [comment]
Created PR - [Pull Reruest](https://github.com/jotes/django-cookies-samesite/pull/21)

**Comment by jotes** [comment]
Fixed in #21
