### ISSUE TITLE
Missing versions 0.6.6 onwards on pypi

### ISSUE THREAD

**Issue by rssujay** [jotes/django-cookies-samesite#40]
* django-cookies-samesite version: 0.6.6
* Django version: -
* Python version: - 
* Operating System: -

### Description

Hello, with the release of 0.7.0, it appears that tags from 0.6.6 onwards were recreated. These versions no longer appear on pypi: https://pypi.org/project/django-cookies-samesite/#history

Hence, this broke our build pipeline which was pinned to version 0.6.6. Thanks for looking into it!

GitHub tags:
![image](https://user-images.githubusercontent.com/40201586/93160286-90f37d00-f742-11ea-9ef1-9029c21ef046.png)

Pypi:
![image](https://user-images.githubusercontent.com/40201586/93160309-9fda2f80-f742-11ea-9b31-29374d250ebf.png)

### What I Did

```
pip install django-cookies-samesite==0.6.6
```

**Comment by jotes** [comment]
@andersk @rssujay  https://github.com/jotes/django-cookies-samesite/issues/38#issuecomment-692535961 I apologize for your problems, I took a wrong decision.

**Comment by rssujay** [comment]
No worries:)
