### ISSUE TITLE
Admin site messages not going away

### ISSUE THREAD

**Issue by unformatt** [jotes/django-cookies-samesite#44]
* django-cookies-samesite version: 0.8.0
* Django version: 1.11.29
* Python version: 2.7.15rc1
* Operating System: Ubuntu 18.04.5 LTS
* Chrome 86.0.4240.80

### Description

Admin messages show up but are never cleared. They keep showing up on every page and accumulating. These messages are stored in client-side cookies (not session variables). This is probably just one symptom of the problem but this is how I'm finding it. 

### What I Did

My settings when I have the problem:

```
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE_FORCE_ALL = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
```

Change to this, then no problem
```
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE_FORCE_ALL = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
```

![image](https://user-images.githubusercontent.com/157132/96803091-56cc6980-13d9-11eb-8471-ddbe3bf0b6b3.png)

**Comment by jotes** [comment]
Hey @unformatt, I'll take a look into this after work. I don't have an idea what's causing that behavior, but I'll find out.

**Comment by jotes** [comment]
I have an idea but I need more time to test it. I'll ping you ASAIC.

**Comment by jotes** [comment]
@unformatt Hey,
Unfortunately, My idea didn't work and I can't reproduce the problem on `1.11.29`.
Could you add more information about how the cookie headers look like when you try to add a new record in your Django admin app?
I suspect that the problem is caused by the fact that browser doesn't reset the cookie responsible for storing the messages.

**Comment by unformatt** [comment]
Hey @jotes, here's a screenshot from the admin login page:

![image](https://user-images.githubusercontent.com/157132/98131496-51ffbf00-1e89-11eb-83c1-05f391880e77.png)

### Request headers

```
GET /admin/login/
Host: [REDACTED]
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
DNT: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=[REDACTED]; _hjid=[REDACTED]; _hjIncludedInSample=1; __tawkuuid=e::[REDACTED]::[REDACTED]::2; __stripe_mid=[REDACTED]; csrftoken=[REDACTED]; messages="[REDACTED]$[[\"__json_message\"\0541\05425\054\"The [REDACTED] was changed successfully. You may edit it again below.\"]\054[\"__json_message\"\0541\05425\054\"The [REDACTED] was changed successfully. You may edit it again below.\"]\054[\"__json_message\"\0541\05425\054\"The [REDACTED] was changed successfully. You may edit it again below.\"]\054[\"__json_message\"\0541\05425\054\"The [REDACTED] was changed successfully. You may edit it again below.\"]\054[\"__json_message\"\0541\05425\054\"The [REDACTED] was changed successfully. You may edit it again below.\"]]"; _gid=[REDACTED]; TawkConnectionTime=0
```

### Response headers

``` 
HTTP/1.1 200 OK
Server: nginx/1.14.0 (Ubuntu)
Date: Wed, 04 Nov 2020 15:32:46 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Expires: Wed, 04 Nov 2020 15:32:45 GMT
Vary: Cookie, Origin
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Set-Cookie: csrftoken=[REDACTED]; expires=Wed, 03-Nov-2021 15:32:46 GMT; Max-Age=31449600; Path=/; SameSite=None; Secure
Set-Cookie: messages=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/; SameSite=None
Content-Encoding: gzip
X-DNS-Prefetch-Control: off
```

**Comment by unformatt** [comment]
If I edit something in the admin, it adds to the current messages list:

### Response headers after editing something

```
HTTP/1.1 302 Found
Server: nginx/1.14.0 (Ubuntu)
Date: Wed, 04 Nov 2020 15:41:13 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Expires: Wed, 04 Nov 2020 15:41:13 GMT
Vary: Origin, Cookie
Location: [REDACTED]
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Set-Cookie: messages="[REDACTED]$[[\"__json_message\"\0541\05425\054\"The [REDACTED] was changed successfully. You may edit it again below.\"]\054[\"__json_message\"\0541\05425\054\"The [REDACTED] was changed successfully. You may edit it again below.\"]\054[\"__json_message\"\0541\05425\054\"The [REDACTED] was changed successfully. You may edit it again below.\"]\054[\"__json_message\"\0541\05425\054\"The [REDACTED] was changed successfully. You may edit it again below.\"]\054[\"__json_message\"\0541\05425\054\"The[REDACTED] was changed successfully. You may edit it again below.\"]\054[\"__json_message\"\0541\05425\054\"The [REDACTED] was changed successfully.\"]]"; httponly; Path=/; SameSite=None; Secure
X-DNS-Prefetch-Control: off
```

**Comment by jotes** [comment]
Hey, sorry @unformatt but I'm too busy at work again, unfortunately. 
@abdul-rafiu do you have an idea what could be the reason of this behavior?

**Comment by rubgombar1** [comment]
Hi!

@unformatt we had the same issue using the same settings than you and we change the setting **SESSION_COOKIE_SAMESITE_FORCE_ALL** to False and works correctly google chrome with the samesite flag and django messages framework in django 1.11.11

The final settings are:
`SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE_FORCE_ALL = False
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True`

I hope that this help you.

Regards!

**Comment by unformatt** [comment]
Thanks @rubgombar1. That worked. Hopefully this doesn't undo the original problem I was trying to fix. After a quick smoke test, everything looks good.
