### ISSUE TITLE
DCS_CSRF_COOKIE_SECURE doesnt work

### ISSUE THREAD

**Issue by oscars17** [jotes/django-cookies-samesite#49]
* django-cookies-samesite version: 0.9.0
* Django version: 2.7
* Python version: 3.7
* Operating System: ubuntu 18

### Description

DCS_CSRF_COOKIE_SECURE = True
DCS_CSRF_COOKIE_SAMESITE = 'None'
doesnt work
![Screenshot from 2021-04-29 17-31-32](https://user-images.githubusercontent.com/57970391/116550959-ce42fe80-a910-11eb-852f-5737a03d42f4.png)

**Comment by oscars17** [comment]
DCS_SESSION_COOKIE_SECURE = True
DCS_SESSION_COOKIE_SAMESITE = 'None'
DCS_SESSION_COOKIE_SAMESITE_FORCE_ALL = True

doesnt work as well

**Comment by oscars17** [comment]
its ok now sry

**Comment by caryyu** [comment]
> DCS_SESSION_COOKIE_SECURE = True DCS_SESSION_COOKIE_SAMESITE = 'None' DCS_SESSION_COOKIE_SAMESITE_FORCE_ALL = True
> 
> doesnt work as well

I don't think this library already supports these settings, from the source code, I only see it is working unless enabling the ssl.
