### ISSUE TITLE
Not working when you change SESSION_COOKIE_NAME

### ISSUE THREAD

**Issue by Rmaan** [jotes/django-cookies-samesite#5]
In Django we can set the session cookie name by setting `SESSION_COOKIE_NAME` in Django settings. Also you can change CSRF cookie name with `CSRF_COOKIE_NAME`.

But django-cookies-samesite will not work because `'sessionid'` and `'csrftoken'` is hard-coded in middleware (unless we add them inside `SESSION_COOKIE_SAMESITE_KEYS`).

**Comment by jotes** [comment]
@antoinelb Sorry, I'm busy in IRL :( I'll release the new version today.
