### ISSUE TITLE
Doesn't support 'None' value

### ISSUE THREAD

**Issue by brianmay** [jotes/django-cookies-samesite#7]
The None value translates to not supplying the header. Under Chrome < 80 not supplying the header corresponds to no restrictions. Under Chrome >= 80, not supplying the header is the same as setting it to Lax. If you want no restrictions you have to set it to "None" not None, but this library does not allow for that.

It would be good if this library supported the "None" value required by the latest standard, so that applications still using older versions of Django won't break.

* https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/
* https://tools.ietf.org/html/draft-west-cookie-incrementalism-00

**Comment by jonespm** [comment]
This was fixed in Django (3.1) via 
https://github.com/django/django/pull/11894
https://github.com/django/django/commit/b33bfc383935cd26e19a2cf71d066ac6edd1425f

So the fix here would be similar. Just adding 'none' to the list.

**Comment by jotes** [comment]
Hey,
I'm sorry that it took so long for me to respond, the real-life overwhelmed me for the past few months and I didn't notice this issue.
I've merged the PR from @jonespm, the new version will be released today on PyPI.

**Comment by jonespm** [comment]
Awesome @jotes thanks! Just want to make sure we have this option come February.

**Comment by jotes** [comment]
@brianmay @jonespm Hey folks, thank you for your patience. The new version (0.3.0) has been released a few moments ago.
